- src/bits.rs
I believe `!` operation on `usize` is not working.
> bits: fix power of 2 calculation

- Cargo.toml
- README.md
Upgrade goblin to 0.0.19. Also add the deps.rs badge into README.
> chore: upgrade crates

- src/lib.rs
- src/machine.rs
It turns out we won't need that much maximum memory initially here. 128MB is quite a waste of resource, this PR changes it now to 16MB.
> feat: Reduce maximum memory to 16M to save resources

- src/instructions/common.rs
- src/instructions/i.rs
- src/instructions/m.rs
- src/instructions/register.rs
- src/instructions/rvc.rs
- src/instructions/utils.rs
- src/lib.rs
- src/machine.rs
- src/runners/interpreter.rs
- src/runners/mod.rs
- src/syscalls/mod.rs
- tests/test_misc.rs
- tests/test_simple.rs
The code here currently has some obstacles that do not favor a JIT implementation:
* Overflow information is exposed outside of register value: https://github.com/nervosnetwork/ckb-vm/blob/ac2b5cf858e30a4080beffa067a8fb9e8085d097/src/instructions/register.rs#L33
* [Certain](https://github.com/nervosnetwork/ckb-vm/blob/master/src/instructions/i.rs#L227) [instruction](https://github.com/nervosnetwork/ckb-vm/blob/master/src/instructions/i.rs#L317) [logic](https://github.com/nervosnetwork/ckb-vm/blob/master/src/instructions/m.rs#L69) is implemented in Rust outside of register types, which makes it hard to JIT
* Basic CoreMachine [contains](https://github.com/nervosnetwork/ckb-vm/blob/ac2b5cf858e30a4080beffa067a8fb9e8085d097/src/machine.rs#L55-L63) too many features that are only needed in …
> refactor: Preparation work for moving into a JIT structure

- src/instructions/common.rs
- src/instructions/i.rs
- src/instructions/m.rs
- src/instructions/register.rs
- src/instructions/rvc.rs
- src/machine.rs
This is actually one tech debt paid due to my inexperience with Rust :(
Previously, `Register` type implements Copy trait, which means we are really copying the register values everywhere. This is not a problem when we are dealing with primitive types such as `u64` or `u32`, but when we are working on a JIT, the register values are actually AST nodes that look like the following:
```rust
#[derive(Debug, Clone)]
pub enum Value {
Imm(u64),
Register(usize),
PcRegister,
Add(Rc<Value>, Rc<Value>),
Sub(Rc<Value>, Rc<Value>),
}
```
Since `Rc` is used here to build recursive enum type, we cannot use copy semantics and have to revert back to move semantics, this PR deals with this change.
> refactor: Change Register type to only implement Clone, not Copy

- src/instructions/common.rs
- src/instructions/i.rs
- src/instructions/m.rs
- src/instructions/mod.rs
- src/instructions/rvc.rs
- src/instructions/utils.rs
- src/machine.rs
- src/syscalls/mod.rs
- tests/test_misc.rs
This PR changes `Machine` trait's generic type to associated type, any function that wants to take a `Machine` as a parameter now no need to be generic over `Register` and `Memory` type.
> refactor: change `Machine` generic type to associated type

- src/decoder.rs
- src/instructions/common.rs
- src/instructions/register.rs
- src/lib.rs
- src/machine.rs
- src/memory/flat.rs
- src/memory/mmu.rs
- src/memory/mod.rs
- src/memory/sparse.rs
- tests/test_minimal.rs
- tests/test_misc.rs
- tests/test_mmu.rs
- tests/test_simple.rs
While #21 ensures most of the logic happens within register type, memory trait is left out, and we did have logic that [happens outside register type](https://github.com/nervosnetwork/ckb-vm/blob/42e0e13e801fd90409b6532f53d899fe7876d30b/src/instructions/common.rs#L178-L180), this is fixed here to make sure JIT can have all the needed information.
> refactor: Ensure memory trait is also using Register types

- .travis.yml
- Cargo.toml
- README.md
- benches/bits_benchmark.rs
- src/bits.rs
```
rounup via remainder    time:   [2.2321 us 2.2439 us 2.2577 us]
change: [-5.5708% -3.8512% -2.2337%] (p = 0.00 < 0.05)
Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
4 (4.00%) high mild
2 (2.00%) high severe
rounup via bit ops      time:   [0.0000 ps 0.0000 ps 0.0000 ps]
change: [-53.351% -6.3284% +86.775%] (p = 0.87 > 0.05)
No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
4 (4.00%) high mild
8 (8.00%) high severe
rounup via multication  time:   [2.4807 us 2.5208 us 2.5662 us]
change: [+4.8590% +7.3068% +9.9176%] (p = 0.00 < 0.05)
Performance has regressed.
Found 11 outliers among 100 measurements (11.00%)
8 (8.00%) high mild
3 (3.00%) high severe
rounup via remainder    time:   [2.3393 us 2.3603 us 2.3835 us]
change: …
```
> refactor: use bits operations to round up/down

- .travis.yml
- src/jit/machine.rs
Since ckb-vm is relatively independent of ckb, we can do this now, and do the actual upgrade later when ckb is moved to Rust 1.33.
> refactor: Use Pin in Rust 1.33 to simplify code

- .travis.yml
- Cargo.toml
- Makefile
- build.rs
- src/lib.rs
- tests/test_jit.rs
This way we can upgrade CKB with latest CKB-VM containing bug fixes, but don't need to worry that JIT related code could bring potential problems for now.
> chore: Make JIT into a feature that can be enabled or disabled

- Cargo.toml
- src/bits.rs
- src/instructions/common.rs
- src/instructions/i.rs
- src/instructions/m.rs
- src/instructions/mod.rs
- src/instructions/rvc.rs
- src/instructions/utils.rs
- src/jit/instructions.rs
- src/jit/machine.rs
- src/machine.rs
- tests/test_simple.rs
Note this is actually at the same level of performance comparing to our currently deployed [version](https://github.com/nervosnetwork/ckb-vm/tree/simple-decoder-cache-64-2) using decoder cache. But the advantage of this solution here, is that we are using fixed length vector instead of a dynamically grown HashMap, hence we will have a fixed upper bound on the memory usage when running any arbitrary scripts.
> Use traces to optimize interpreter performance

- src/memory/flat.rs
As far as I can know, `slice_ptr` should start from `addr`.
> fix: flat memory implementation stores byte in wrong locations

- src/instructions/execute.rs
Previously, we were doing the cond operation first on the PC offsets,
then add the base PC address to form the final AST node. The problem
with this, is that the base PC addresses and offsets are both
immediate values in most instructions. So we can just calculate the
final PC addresses first, then apply the cond operation. In a normal
interpreter this won't matter, but for JIT or AOT implementation, this
makes sure we can have simpler AST node to apply optimizations
> refactor: calculate address first before cond operation

- src/instructions/execute.rs
The old codes:
```rs
let value = &machine.registers()[i.rs2()]; // immutable borrow machine
update_register(machine, i.rd(), value.clone()); // mutable borrow machine in first argument, and immutable borrow in third argument "value"
```
> chore: fix a bad way to using machine

- benches/vm_benchmark.rs
Since the method `run` accepts `Bytes` instead of `Vec<u8>`
> fix: fix the broken bench tests

- src/bits.rs
- src/lib.rs
- src/machine/trace.rs
Implementation is only different in ways that are inconsequential for how they
are used here.
Custom:
```
#[inline(always)]
pub fn power_of_2(x: usize) -> bool {
x > 0 && ((x & (x - 1)) == 0)
}
```
std:
```
#[inline]
pub fn is_power_of_two(self) -> bool {
(self.wrapping_sub(1)) & self == 0 && !(self == 0)
}
```
> Replace custom power_of_2 function with std

- .travis.yml
- Makefile
This is adapted from #66 thanks to @u2's help!
I originally rejected the idea of adding coverage job in #66 but upon further consideration, that's a mistake, we should add coverage job in this repo since:
* Cross-posting coverage report from another repository is very tricky to get right
* While test suite repo contains a lot of useful and complete tests, the tests included in this repo is a good supplement for invalid cases
* With CI job here, bugs in PRs can be detected earlier
> Add coverage CI job containing full CKB VM test suite

- .travis.yml
- src/bits.rs
- src/decoder.rs
- src/instructions/common.rs
- src/instructions/execute.rs
- src/instructions/i.rs
- src/instructions/mod.rs
- src/instructions/register.rs
- src/jit/machine.rs
- src/jit/tracer.rs
- src/jit/value.rs
- src/machine/asm/mod.rs
- src/machine/mod.rs
- src/machine/trace.rs
- src/memory/flat.rs
- src/memory/mod.rs
- src/memory/sparse.rs
- src/memory/wxorx.rs
`usize` is a tricky part since it has different widths across 32-bit vs 64-bit architectures. This PR tries to remove the use of usize from the parts that are making sense. After this PR, we should only be using usize where we have to(such as indexing arrays), and constants where we know no overflows would occur.
> Eliminate as much usize as making sense from CKB VM

- .travis.yml
By default codecov would generate a codecov report and if the coverage is less than original, rejects the CI check. This PR changes the code so we are skipping codecov check in PR, but still do the coverage check when merged to develop
> feat: Do not trigger coverage jobs in PRs

- src/machine/asm/mod.rs
- src/machine/mod.rs
- src/memory/mod.rs
- src/memory/sparse.rs
- src/memory/wxorx.rs
There was already an implementation of round_page_down that duplicated rounddown. This cleanup patch adds round_page_up and makes all rounddown / roundup uses call the round_page versions.
> Replace uses of rounddown / roundup with round_page_down / round_page_up

- codecov.yml
Right now any percentage of coverage drop will trigger a codecov failure. This PR adds reasonable codecov target for now. We can bump the standard here later when we have a more comprehensive test suite.
> feat: Set codecov coverage target

- Cargo.toml
- benches/bits_benchmark.rs
- benches/vm_benchmark.rs
This PR includes three small changes:
- chore(deps): bump criterion from 0.2.11 to 0.3.0
- chore: typo
- chore: cfg criterion_group
> Dependabot/cargo/criterion 0.3.0

- src/machine/asm/mod.rs
- src/machine/mod.rs
- src/machine/trace.rs
- tests/test_simple.rs
This allows us to charge proper cycles for bytes loaded via the program at CKB side.
> feat: Return loaded program consumed bytes

- Cargo.toml
- src/error.rs
- src/lib.rs
This is pretty important for interop with other libraries.
I used derive_more for this, which is a fairly hefty proc macro. It could also be open-coded.
> Implement StdError for Error

- definitions/src/asm.rs
- src/machine/asm/execute.S
- src/machine/trace.rs
The previous slot calculation algorithm we use is optimized for large sequential programs. While this works for simpler cases, it often results in address conflicts in terms of programs with frequent branches. This PR changes the code to a new algorithm that balances between small basic blocks and large code segments. For our most common secp256k1 verification, this reduces ~15% of running time:
```
Benchmarking interpret secp256k1_bench via assembly: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 12.7s or reduce sample count to 40
interpret secp256k1_bench via assembly
time:   [2.5024 ms 2.5031 ms 2.5038 ms]
change: [-16.289% -16.251% -16.212%] (p = 0.00 < 0.05)
Performance has improved.
Found 7 outliers among 100 …
```
> perf: Tweak slot calculation algorithm
